### ISSUE TITLE
Drop `item.when` and `item.delete`. Use `item.state` instead for `apt_preferences__list`.

### ISSUE THREAD

**Issue by ypid** [debops/ansible-apt_preferences#12]
`item.when` and `item.delete` are used by many of the core DebOps roles. This seems to be redundant and can better be expressed with `item.state` with the values `present` (default) or `absent`. I guess this is still legacy or am I missing something?

**Comment by drybjed** [comment]
I suppose it's all somewhat confusing right now... It looks like I tend to use these:

- `item.state`: with `present` and `absent`, per Ansible conventions. This usually creates or removes things automatically on each Ansible pass as configured. Configuration is usually done by hand via Ansible inventory, ie. user choice.

- `item.when`: a boolean `True`/`False` variable, similar to what `when:` condition does in Ansible tasks. This usually activates code generation conditionally by detecting some facts from Ansible or other roles. I suppose this could be changed to `item.state` with `present` and `absent` values applied using a condition.

- `item.delete`: this is a boolean, usually `False`, which doesn't affect anything until it's set to `True`, at which point it usually removes a particular configuration file. It's usually set via Ansible inventory (user choice), and if not set basically leaves things "as is", not touching the configuration if not needed.

I suppose it's all slightly different variants of basically creating or deleting configuration, some of it done conditionally, and some by user intervention. Since I started doing conditions more in `defaults/main.yml` instead of templates or task files, some of it could be merged together. For example, by default a variable is resolved conditionally to a boolean value, but can be overriden using inventory if necessary. However, using `present` or `absent` feels somewhat wrong to me, and instead I preffer `True` or `False`, which are boolean and can be tested via `|bool` filter easily.

**Comment by ypid** [comment]
#### Pro

* More compact, less redundancy and more explicit. When using the `item.state` users and we as role writes will be forced to handle all cases. Example:

  ```YAML
  example__pro_state_argument:
    - name: 'fnord'
      state: '{{ "present" if (example__pro_state_argument_bool | bool) else "absent" }}'
  ```

  ```YAML
  example__contra_state_argument:
    - name: 'fnord'
      when:   '{{ (example__pro_state_argument_bool | bool) }}'
      delete: '{{ not (example__pro_state_argument_bool | bool) }}'
  ```

* More to think about when writing roles. Not really a big deal but I just reallizced that `debops.apt_preferences` does not [behave](https://github.com/debops/ansible-apt_preferences/blob/f95dbf3179462a3569282523d9f4a089974f12e8/tasks/main.yml#L54-L73) according to [it’s documentation](http://docs.debops.org/en/latest/ansible/roles/ansible-apt_preferences/docs/defaults-configuration.html#apt-preferences-list) (when is never checked in the tasks).


* Usually, there are only two states to express (in the Ansible commonly called 'present' and 'absent'). But we are using two booleans meaning they can express four states.

  * True, True case: Would need to be handled by preferring delete state for example, but this conflict could not occur with state.

    ```YAML
    example__something:
      - name: 'fnord'
        when: True
        delete: True
    ```

  * False, False case: This does not seem to be declarative. What if `when` was set to True previously? False, False will leave the option set to True in most implementations I would assume.

    ```YAML
    example__something:
      - name: 'fnord'
        when: False
        delete: False
    ```

* The boolean filter is limited in that it will evaluate everything to `False` which is not `True` or a few special values. No real safety check there except when it is used as bare word like `when: True`. Spell checking in your editor will probably catch that :wink: But I get your point. There are certainly also times when we get the states wrong.

#### Contra

* "Fixed datatype" -> Boolean. That appeals very nice


#### Conclusion

Switching to `item.state` will make evaluating the `item.state` in roles less error prone and more explicit.

#### Alternative

Only using one boolean variable like `item.present`. This is also declarative as well. Something to discuss I guess.
